version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hiv_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/hiv_db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
volumes:
  db_data:
